[[datasets]]

[[datasets.subsets]]
num_repeats = 20
image_dir = "/content/drive/MyDrive/Loras/mensa-food/dataset"

[general]
resolution = 1024
shuffle_caption = true
keep_tokens = 1
flip_aug = true
color_aug = true
caption_extension = ".txt"
enable_bucket = true
bucket_reso_steps = 64
bucket_no_upscale = false
min_bucket_reso = 320
max_bucket_reso = 1280
